import ISelectOption from "../interfaces/ISelectOption";

export const CountryOption: ISelectOption[] = [
    { id: 1, label: "Afghanistan", value: "Afghanistan" },
    { id: 2, label: "Albania", value: "Albania" },
    { id: 3, label: "Algeria", value: "Algeria" },
    { id: 4, label: "American", value: "American" },
    { id: 5, label: "Andorra", value: "Andorra" },
    { id: 6, label: "Angola", value: "Angola" },
    { id: 7, label: "Antarctica", value: "Antarctica" },
    { id: 8, label: "Argentina", value: "Argentina" },
    { id: 9, label: "Aruba", value: "Aruba" },
    { id: 10, label: "Australia", value: "Australia" },
    { id: 11, label: "Bahamas", value: "Bahamas" },
    { id: 12, label: "Bangladesh", value: "Bangladesh" },
    { id: 13, label: "Belarus", value: "Belarus" },
    { id: 14, label: "Benin", value: "Benin" },
    { id: 15, label: "Bhutan", value: "Bhutan" },
    { id: 16, label: "Bolivia", value: "Bolivia" },
    { id: 17, label: "Botswana", value: "Botswana" },
    { id: 18, label: "Brazil", value: "Brazil" },
    { id: 19, label: "Bulgaria", value: "Bulgaria" },
    { id: 20, label: "Cambodia", value: "Cambodia" },
    { id: 21, label: "Canada", value: "Canada" },
    { id: 22, label: "Central African Republic", value: "Central African Republic" },
    { id: 23, label: "Chile", value: "Chile" },
    { id: 24, label: "China", value: "China" },
    { id: 25, label: "Colombia", value: "Colombia" },
    { id: 26, label: "Costa Rica", value: "Costa Rica" },
    { id: 27, label: "Cuba", value: "Cuba" },
    { id: 28, label: "Denmark", value: "Denmark" },
    { id: 29, label: "Dominica", value: "Dominica" },
    { id: 30, label: "Ecuador", value: "Ecuador" },
    { id: 31, label: "Egypt", value: "Egypt" },
    { id: 32, label: "Estonia", value: "Estonia" },
    { id: 33, label: "Faroe Islands", value: "Faroe Islands" },
    { id: 34, label: "French", value: "French" },
    { id: 35, label: "Gambia", value: "Gambia" },
    { id: 36, label: "Germany", value: "Germany" },
    { id: 37, label: "Greenland", value: "Greenland" },
    { id: 38, label: "Guernsey", value: "Guernsey" },
    { id: 39, label: "Haiti", value: "Haiti" },
    { id: 40, label: "Hong Kong", value: "Hong Kong" },
    { id: 41, label: "Hungary", value: "Hungary" },
    { id: 42, label: "Iceland", value: "Iceland" },
    { id: 43, label: "India", value: "India" },
    { id: 44, label: "Indonesia", value: "Indonesia" },
    { id: 45, label: "Iran", value: "Iran" },
    { id: 46, label: "Iraq", value: "Iraq" },
    { id: 47, label: "Ireland", value: "Ireland" },
    { id: 48, label: "Italy", value: "Italy" },
    { id: 49, label: "Japan", value: "Japan" },
    { id: 50, label: "Kazakhstan", value: "Kazakhstan" },
    { id: 51, label: "Korea", value: "Korea" },
    { id: 52, label: "Lao", value: "Lao" },
    { id: 53, label: "Luxembourg", value: "Luxembourg" },
    { id: 54, label: "Macao", value: "Macao" },
    { id: 55, label: "Malaysia", value: "Malaysia" },
    { id: 56, label: "Marshall Islands", value: "Marshall Islands" },
    { id: 57, label: "Mexico", value: "Mexico" },
    { id: 58, label: "Mongolia", value: "Mongolia" },
    { id: 59, label: "Myanmar", value: "Myanmar" },
    { id: 60, label: "Nepal", value: "Nepal" },
    { id: 61, label: "Netherlands", value: "Netherlands" },
    { id: 62, label: "New Zealand", value: "New Zealand" },
    { id: 63, label: "Norfolk Island", value: "Norfolk Island" },
    { id: 64, label: "Norway", value: "Norway" },
    { id: 65, label: "Oman", value: "Oman" },
    { id: 66, label: "Pakistan", value: "Pakistan" },
    { id: 67, label: "Peru", value: "Peru" },
    { id: 68, label: "Philippines", value: "Philippines" },
    { id: 69, label: "Poland", value: "Poland" },
    { id: 70, label: "Qatar", value: "Qatar" },
    { id: 71, label: "Romania", value: "Romania" },
    { id: 72, label: "Russia", value: "Russia" },
    { id: 73, label: "San Marino", value: "San Marino" },
    { id: 74, label: "Serbia", value: "Serbia" },
    { id: 75, label: "Singapore", value: "Singapore" },
    { id: 76, label: "Somalia", value: "Somalia" },
    { id: 77, label: "Sudan", value: "Sudan" },
    { id: 78, label: "Eswatini", value: "Eswatini" },
    { id: 79, label: "Switzerland", value: "Switzerland" },
    { id: 80, label: "Taiwan", value: "Taiwan" },
    { id: 81, label: "Thailand", value: "Thailand" },
    { id: 82, label: "Tonga", value: "Tonga" },
    { id: 83, label: "Turks and Caicos Islands", value: "Turks and Caicos Islands" },
    { id: 84, label: "Ukraine", value: "Ukraine" },
    { id: 85, label: "United States", value: "United States" },
    { id: 86, label: "Uzbekistan", value: "Uzbekistan" },
    { id: 87, label: "Vanuatu", value: "Vanuatu" },
    { id: 88, label: "Vietnam", value: "Vietnam" },
    { id: 89, label: "Western Sahara", value: "Western Sahara" },
    { id: 90, label: "Yemen", value: "Yemen" },
    { id: 91, label: "Zambia", value: "Zambia" },
    { id: 92, label: "Zimbabwe", value: "Zimbabwe" },
]